### ISSUE TITLE
Example for page-transition

### ISSUE THREAD

**Issue by SimonDegraeve** [andreypopp/rrouter#1]
Hi, I realise this package is still in heavy development but could give an example how to implement [page-transition](https://github.com/andreypopp/react-router-page-transition) with this new router. Or give me some directions so I can try to do it by myself. 

Thanks

**Comment by andreypopp** [comment]
Hi,

I've pushed an example with animated page transition to examples —
http://andreypopp.github.io/rrouter/examples/animated-page-transition.html

Let me know if you have some feedback!

On Sun, May 25, 2014 at 4:18 AM, Simon Degraeve notifications@github.comwrote:

> Hi, I realise this package is still in heavy development but could give an
> example how to implement page-transitionhttps://github.com/andreypopp/react-router-page-transitionwith this new router. Or give me some directions so I can try to do it by
> myself.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andreypopp/rrouter/issues/1
> .

## 

Andrey Popp / 8mayday@gmail.com

**Comment by SimonDegraeve** [comment]
Good I will try this tomorrow. Thank you for your concern.

**Comment by andreypopp** [comment]
Closing this, feel free to reopen if have any more questions.
