### ISSUE TITLE
app with nav example

### ISSUE THREAD

**Issue by ahdinosaur** [andreypopp/rrouter#12]
like [react-router's example](https://github.com/rpflorence/react-router#example).

would be very appreciated. :)

**Comment by ahdinosaur** [comment]
when you add dataDependencies to this example, it hits the error

> Error: Invariant Violation: replaceProps(...): You called `setProps` or `replaceProps` on a component with a parent. This is an anti-pattern since props will get reactively updated when rendered. Instead, change the owner's `render` method to pass the correct value as props to the component where it is created.

because the route view being set with the data is inside the App view.

**Comment by andreypopp** [comment]
Can you provide an example? It seems that there's incorrect usage of `setProps` but rrouter doesn't use this method at all.

**Comment by ahdinosaur** [comment]
oops, my bad. ignore this, thanks for the response.
