### ISSUE TITLE
querystring support

### ISSUE THREAD

**Issue by stereosteve** [andreypopp/rrouter#15]
I have a search route that uses query parameters, and uses a promise to fetch the search results.

If the path does not change, calling `navigate` will do nothing even if the query params have changed:

```
this.navigate('/search?' + encodedQuery)
```

Do you have plans to support query strings?

**Comment by stereosteve** [comment]
Workaround is to pass the encoded querystring as a route param without using `?`:

```
<Route path="/search/:qs" view={SearchApp} resultsPromise={fetchResults} />
```

```
this.navigate('/search/' + encodedQs)
```

**Comment by simenbrekken** [comment]
@stereosteve I've begun implementing querystring support via #27

**Comment by andreypopp** [comment]
Now implemented.
