### ISSUE TITLE
Unclear error `no routes found in context`

### ISSUE THREAD

**Issue by MoOx** [andreypopp/rrouter#16]
I just go a `Error: Invariant Violation: no routes found in context`.
The error message is unclear (compared to React error messages :D )
Here is some of my code

``` js
/** @jsx React.DOM */

module React from "react"
module RRouter from "rrouter"

var Routes = RRouter.Routes
var Route = RRouter.Route

import {Fc} from "./fc"
var fc = React.renderComponent(
  <Fc />,
  document.querySelector(".fc-App")
)

import {FcHomePage} from "./fc/pages/homepage"
import {FcPageAbout} from "./fc/pages/about"

var routes = (
  <Routes>
    <Route name="main" path="/" view={FcHomePage} />
    <Route name="about" path="/about" view={FcPageAbout} />
  </Routes>
)

export default function startRouter() {
  RRouter.start(routes, function(view) {
    fc.updatePage(view)
  })
}
```

`fc.updatePage` is just a `setProp`
then I use

``` js
import router from "./components/router"
///...
router()
```

**Comment by andreypopp** [comment]
I'll fix the error message.

RRouter is meant to be used so you create entire app inside `RRouter.start` callback, just move `React.renderComponent` there:

```
RRouter.start(routes, function(view) {
  var fc = React.renderComponent(
    <Fc page={view} />,
    document.querySelector(".fc-App")
  )
```

This will have the same effect for React but for RRouter it will make possible to provide you application component (`<Fc />`) with information on routes so it can use `<Link />` component.

Also, `setProps()` will be probably deprecated in the future.

**Comment by MoOx** [comment]
Thanks for the fast answer.
This works like a charm ! I've removed my `updatePage` method.
