### ISSUE TITLE
Add a prop to Link when there are "active"

### ISSUE THREAD

**Issue by MoOx** [andreypopp/rrouter#19]
It would be nice to get something like an (dom) attribute or an additional class.
It will be really convenient to add some CSS for current active link.
Is this something relevant in the `<Link>` component ?

**Comment by andreypopp** [comment]
Not at moment.

I agree that could be useful but I don't think we can solve this in general. Maybe we should just document how to create custom `Link` components.

**Comment by MoOx** [comment]
Good point.

**Comment by andreypopp** [comment]
As #24 merged, we provide `LinkMixin` which can be used to implement "highlihted link". We need an example though.
