### ISSUE TITLE
Error in doc: "data-fetching example"?

### ISSUE THREAD

**Issue by SimonDegraeve** [andreypopp/rrouter#2]
Hi
I dont know if its a typo or me who didn't get it but in the data-fetching example you have this routes

```
<Routes promiseItems={fetchItemsList} path="/items" view={Items}>
    <Route promiseItem={fetchItem} path="/items/:itemId" view={Item} />
 </Routes>
```

and then in nested routes:

```
<Route name="items" path="/items" view={Items}>
    <Route name="all" path="/all" view={AllItem}>
    <Route name="item" path="/:id" view={Item}>
</Route>
```

The first example should be a nested route? In this case "/items' is duplicate. 
Or if its not a bug maybe you should change the first example to match the example in "Routing configuration" and "composing-routes" to be more consistent.

Also in "navigation example", there is no Routes (plural) tag only singular. Is it on purpose?

**Comment by SimonDegraeve** [comment]
Is little bit confusing depending on the examples: sometimes plural tag, some times only singular

**Comment by andreypopp** [comment]
> I dont know if its a typo or me who didn't get it but in the data-fetching example you have this 

Fixed, thanks. That's indeed nested routes and so `items` isn't necessary in the inner route's path.

> Also in "navigation example", there is no Routes (plural) tag only singular. Is it on purpose?

Fixed!

> Is little bit confusing depending on the examples: sometimes plural tag, some times only singular

So `Routes` and `Route` are almost interchangeable, unless you start composing routes. I'll document further what means what. But I agree that I should probably change `Routes` to something more descriptive...

**Comment by andreypopp** [comment]
@SimonDegraeve feel free to open PRs with fixes to docs!
