### ISSUE TITLE
subviews: pass view factories instead of instantiated subviews to views

### ISSUE THREAD

**Issue by andreypopp** [andreypopp/rrouter#22]
That way we can:
- allow injecting additional props by views
- allow flowing view's context into subviews

as per IRC discussion with @MattAitchison

**Comment by mattatcha** [comment]
Do you think cloning the component could work too?
http://facebook.github.io/react/docs/clone-with-props.html

**Comment by andreypopp** [comment]
Yes, cloning will work too.

**Comment by simenbrekken** [comment]
As far as I understand the concept the idea is to go from this:

``` html
<div>
    {view}
</div>
```

to:

``` html
var view = this.props.view
...
<div>
    <view foo={this.props.foo} />
</div>
```

If that's the case it would be great if the view descriptor's default value is a function that simply returns null so it's possible to avoid having to do:

``` html
<div>
    {view && <view foo={this.props.foo} />}
</div>
```

**Comment by andreypopp** [comment]
@sbrekken that's convenient but makes impl complex because we need to know all possible props which can be passed to a view. Now we can only traverse the matched trace.

I think it would be better implemented via standard React mechanism: `getDefaultProps`:

```
var emptyFunction = require('react/lib/emptyFunction')

var View = React.createClass({
  getDefaultProps: function() {
    return {subView: emptyFunction}
  }
  ...
})
```

**Comment by simenbrekken** [comment]
It should be noted that for some reason custom components need to be capitalized.

This snippet:

``` html
render: function() {
  var details = this.props.details

  return (
    <div>
      <details foo="bar" />
    </div>
    …
```

Will get transpiled to this:

``` html
render: function() {
  var details = this.props.details

  return (
    React.DOM.div(
      React.DOM.details({foo: "bar"})
    )
    …
```

Whilst when capitalizing details:

``` html
render: function() {
  var Details = this.props.details

  return (
    <div>
      <Details foo="bar" />
    </div>
    …
```

It gets correctly transpiled

``` html
render: function() {
  var Details = this.props.details

  return (
    React.DOM.div(
      Details({foo: "bar"})
    )
    …
```

**Comment by mattatcha** [comment]
Using the following will allow it to work though.

```
  getDefaultProps: function() {
    return {detailView: function() { }}
  },
```

**Comment by andreypopp** [comment]
@sbrekken I believe this is the case with `<details />` which is whitelisted as a DOM component. But yeah, I should fix the example code (master-detail). Also when 0.11 lands we can do:

```
<this.props.details />
```

**Comment by simenbrekken** [comment]
Yes, I was running this with #27 merged.
