### ISSUE TITLE
Parent components

### ISSUE THREAD

**Issue by cleercode** [andreypopp/rrouter#23]
I'm curious how this router is supposed to be used with components that should remain static apart from the routes.

I have a setup like this (pseudocode):

```
<App>
  <Navigation />
  {view}
  <maybe some other random elements>
</App>
```

I'm using this render function:

```
RRouter.HashRouting.start(routes, function(view) {
  React.renderComponent(<App view={view} />, document.body);
});
```

is this a bad way to do things? The problem I've realized is that I need `<Navigation />` to be aware of URL parameters to highlight the current view, but only the view components are aware of these parameters as props.

Should I instead incorporate `<Navigation />` into the all of the view components? Seems kind of redundant, but maybe that's the way it's supposed to be done?

**Comment by mattatcha** [comment]
Here is a link on how I am doing it.  I hope it helps!

https://gist.github.com/MattAitchison/9cdc5d3c350d961e304c

**Comment by andreypopp** [comment]
You can use `RRouter.RoutingContextMixin` to get access to a current match via `this.getMatch()` method. That way your `<Navigation />` component can be placed directly inside `<App />`.

**Comment by simenbrekken** [comment]
@cleercode Here's a quick example:

``` html
var MenuItem = React.createClass({
  mixins: [Router.NavigateMixin],

  isSelected: function() {
    var url = this.props.url
    var current = this.getUrl()

    // Non-greedy match
    return url === '/' ? url === current : current.indexOf(url) === 0
  },

  render: function() {
    var className = this.isSelected() ? this.props.selectedClassName : null

    return (
      <li className={className}>
        <Link href={this.props.url}>{this.props.children}</Link>
      </li>
    )
  }
})

<MenuItem url="/home">Home</MenuItem>
<MenuItem url="/products">Products</MenuItem>
```
