### ISSUE TITLE
Provide ES5 compatible npm module by default

### ISSUE THREAD

**Issue by simenbrekken** [andreypopp/rrouter#29]
Maybe simply rename `lib` to `src` and compile sources to `lib` using `npm prepublish` and `react-tools/bin/jsx`?

**Comment by simenbrekken** [comment]
I've got a [Makefile](https://github.com/unfold/rrouter/blob/master/Makefile#L7) with the necessary target.

**Comment by andreypopp** [comment]
Should also fix `main` key in `package.json`.

**Comment by andreypopp** [comment]
0.3.0 contains es5 code
