### ISSUE TITLE
Render called twice for fulfilled view promises

### ISSUE THREAD

**Issue by simenbrekken** [andreypopp/rrouter#30]
Even if a views promise properties are all resolved, `renderView` is still called twice even if all the views properties have previously been resolved.

**Comment by andreypopp** [comment]
Hm.. can't reproduce https://github.com/andreypopp/rrouter/blob/master/lib/routing/__tests__/PathnameRouting-test.js#L238-L280

**Comment by andreypopp** [comment]
Are you sure you are returning fulfulled promises?

For example this one is considered fulfulled:

```
var promise = Promise.resolve(1);
```

and this one is not:

```
var promise = Promise.resolve(1).then(function(x) { return x + 1 });
```

**Comment by simenbrekken** [comment]
I'm having problems reproducing this without my surrounding app so I'm closing this for now.
