### ISSUE TITLE
Parent components and rendering to document

### ISSUE THREAD

**Issue by callum** [andreypopp/rrouter#34]
Re: https://github.com/andreypopp/rrouter/issues/23

Using a setup similar to the above my app renders on the server using data dependencies. I get some weird issues on the client-side. In the browser the component is rendered like this:

``` js
RRouter.start(routes, function(view) {
  React.renderComponent(<App view={view} />, document);
});
```

And the server:

``` js
RRouter.route(routes, req.url).then(function(execute) {
  execute(function(view) {
    if (!view) {
      return next();
    }

    var app = App({view: view});
    res.end("<!doctype html>" + React.renderComponentToString(app));
  });
});
```

One of the routes:

``` js
function fetchData() {
  return APIRequest("data");
}

module.exports = (
  <Route>
    <Route
      path="/"
      view={Main}
      dataPromise={fetchData}
    />
  </Route>
);
```

It renders fine most of the time. Some times duplicate data is output in the `Main` component. But I'm always getting:

> Error: Invariant Violation: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side.

![stacktrace](https://cloud.githubusercontent.com/assets/1245446/3280711/100d43a2-f478-11e3-9286-4b96f1402eda.png)

Doesn't seem to be a problem when `view` is rendered directly to `document` without the parent `App` component.

Can anyone explain this?

**Comment by callum** [comment]
I think the inconsistency might be in `APIRequest`; that the server is getting back slightly different data than the client. On the server the `requests` library is used to call the API, and on the client it's swapped out with `browser-requests`.

How do you handle situations where props passed on the server differ slightly from those passed on the client? Let's say a record is added between rendering on the server and instantiating on the client. I guess this is relevant:

https://groups.google.com/forum/#!msg/reactjs/ydPtKj8NYN8/unE2_AUhAHcJ

**Comment by andreypopp** [comment]
You should create components with **the same** props both on server and on client to make React work with server-rendered markup. The best way to do it is to transfer all props to browser as JSON data (embedding it in `<script>` element in page).

**Comment by callum** [comment]
So the data fetching functionality of rrouter doesn't work with server rendering, unless you can be absolutely sure you're receiving the same data. What might a solution look like for passing JSON to the browser? Is it somehow possible to extract all the data passed to a component as props using the `*Promise` pattern? There doesn't seem like a clean way to do this.

**Comment by simenbrekken** [comment]
@callum Here's a bit dated example of how I'm fetching data on the server: https://gist.github.com/sbrekken/c4afbf3631f2edf46a48

**Comment by callum** [comment]
@sbrekken nice. Can't help but think there is a more elegant way though. Can I see how that JSON is then passed to your component via Rrouter in the browser?

**Comment by simenbrekken** [comment]
@callum Basically like this:

``` javascript
var shared = typeof window !== 'undefined' ? window._shared : {}

var loadSomething() {
  var something = shared.something

  if (something) {
    delete shared.something

    return Promise.resolve(something)
  } else {
    ... ajax the things
  }
}
```

Recently though I've switched to using singleton stores with static methods on views to fetch data.

``` javascript
// Server
var middleware = function(routes) {
  return function(req, res, next) {
    var path = req.path
    var query = req.query
    var match = Router.matchRoutes(routes, path, query)

    if (!match.route) return next()

    var props = lodash.reduceRight(match.activeTrace, function(props, trace) {
      return lodash.assign(props, trace.match)
    }, {})

    var view = match.route.view
    var promise

    if (view.fetchData) {
      promise = view.fetchData(props, path, query)
    } else {
      promise = Promise.resolve()
    }

    promise.then(function(data) {
      lodash.assign(props, data)

      var locals = {
        markup: React.renderComponentToString(Application(view(props))),
        shared: JSON.stringify({initialData: data})
      }

      res.send(template(locals))
    })
  }
}

// Client entry 
window.onload = function() {
  Router.start(routes, function(view, match) {
    var initialData = window._shared.initialData
    var context = {match: match, routing: this, routes: this.routes}
    var promise

    if (initialData) {
      console.debug('Got initial data:', initialData)

      promise = Promise.resolve(initialData)

      window._shared.initialData = null
    } else if (view.constructor.fetchData) {
      console.debug('Fetching data...')

      promise = view.constructor.fetchData(view.props)
    } else {
      promise = Promise.resolve()
    }

    promise.then(function(data) {
      lodash.assign(view.props, data)

      console.debug('Rendering', view.constructor.displayName, 'with data:', data)

      React.withContext(context, function()  {
        React.renderComponent(Application({view: view}), document.body)
      })
    })
  })
}
```

**Comment by callum** [comment]
@andreypopp it'd be great to see an example added here: http://andreypopp.github.io/rrouter/server-side-rendering.html

Using @sbrekken's solution I get this error on the server:

```
Possibly unhandled Error: Invariant Violation: no routing found in context
```

This is a result of using `Link`.

**Comment by andreypopp** [comment]
Yes, this was fixed in master (among some other API changes).
