### ISSUE TITLE
Nested routes don't pass params

### ISSUE THREAD

**Issue by callum** [andreypopp/rrouter#39]
I have a link:

``` js
<Link
  to="/collections/collection/playlists/playlist"
  collection={this.props.collectionId}
  playlist={playlist.id}>
  View all
</Link>
```

With a routing configuration like this:

``` js
<Route name="collections" path="/collections"
       view={CollectionsIndex} dataPromise={$promise}>
  <Route name="collection" path=":collection" view={CollectionsShow}
         dataPromise={$promise}>
    <Route name="playlists" path="playlists">
      <Route name="playlist" path=":playlist" view={CollectionsPlayer}
             dataPromise={$promise} />
    </Route>
  </Route>
</Route>
```

When routed to `/collections/collection/playlists/playlist` the promise is only passed the `playlist` ID and not the `collection` ID. Is there a specific reason it works in this way? To make an API request I need collection and playlist IDs.

**Comment by callum** [comment]
Been trying to trace this to see what's happening.

![screen shot 2014-07-31 at 14 34 34](https://cloud.githubusercontent.com/assets/1245446/3764995/8ec1d86c-18b7-11e4-99e4-9a01b9277748.png)

Seems that all of the params I'm looking for are there. How can we make them passed to a `*Promise` handler? In this case, I would expect that the handler for `dataPromise` on my playlist route to receive those params. Something like this:

``` js
function $promise(params) {
  // /collections/:collection/playlists/:playlist
  return queryData(params.collection, params.playlist);
}
```

But only playlist is set. Any clues @andreypopp? I can't work out if this is expected behaviour.

**Comment by callum** [comment]
I've set up a small isolated use case based on one of your examples here:

https://github.com/callum/rrouter-nested-routes

https://github.com/callum/rrouter-nested-routes/blob/master/index.js#L38-L40

**Comment by clickblipclick** [comment]
Running into the same issue. Thanks for putting together the example.
