### ISSUE TITLE
Extending Route

### ISSUE THREAD

**Issue by brendangibson** [andreypopp/rrouter#41]
I have a large number of routes that I want to share a number of common props

e.g

<Routes>
    <Route name='a' aProp='myProp'/>
    <Route name='b' aProp='myProp'/>
    <Route name='c' aProp='myProp'/>
    <Route name='d' anotherProp='anotherProp'/>
</Routes>

I don't want to have to add "aProp='myProp'" to every single Route, so I tried

MyRoute = function(props) {
    props.aProp='myProp';
    return Route(props);
}

<Routes>
  <MyRoute name='a'/>
  <MyRoute name='b'/>
  <MyRoute name='c'/>
  <Route name='d' anotherProp='anotherProp'/>
</Routes>

but that gives me errors. (length undefined etc)

Is there a nice way to achieve this?

**Comment by andreypopp** [comment]
You need to pass all arguments:

```
function MyRoute(props) {
  props.aProp = 'myProp';
  return Route.apply(Route, arguments);
}
```

**Comment by brendangibson** [comment]
Thanks Andrey,

That worked for me.
