### ISSUE TITLE
Render view w/o waiting for data deps to resolve

### ISSUE THREAD

**Issue by andreypopp** [andreypopp/rrouter#8]
This will allow to render a preloader while data deps are resolved.

Decide what to pass to views instead of unresolved yet props
- **null** — good because make components unaware of where data comes from, that means data isn't there and that's all
- **promise** — good because if promise can be tracked for progress we can render complex loading indicators with percents complete or progress bars
- **both** — null as propName, promise as propNamePromise

**Comment by simenbrekken** [comment]
I'd go with either **null** or **both**, depending on a promise might be a bit of an overkill.

**Comment by andreypopp** [comment]
So I implemented it to render view progressively as data becomes available for each step it re-renders view. See http://andreypopp.github.io/rrouter/examples/master-detail.html example which demonstrates it.

**Comment by simenbrekken** [comment]
This change messes up animations. Basically for every route change promise props are reset back to null causing `render` to be called twice, once for the reset and then one or more times as data comes in.

I can't think of a better way than to be able to override data fetching in special cases like this. I was thinking something along the lines of:

``` html
function myFetchData(params, promises) {
  return Promise.map(promises)
}
…

<Component fetchData={myFetchData} />
```

This could also be used for caching, request consolidation etc.

**Comment by andreypopp** [comment]
There's a trick currently, if you return fulfilled promises (`isFulfilled() === true`, created with `Promise.resolve(data)`) then rrouter is smart enough not to wait for it and extracts its value directly so there will be no additional re-render. See master-detail example which does exactly that — its `getItem` and `getItems` functions return fulfilled promises in case values are cached.

**Comment by andreypopp** [comment]
Also we can invent a prop on `Route` which will instruct rrouter not to issue an update when value for this route is fetched and instead update at once on completion.

**Comment by simenbrekken** [comment]
The problem arises when you have multiple promises that complete in different orders, at some point I have to be able to control when the main `fetchData` promise gets resolved. For some views it may be desirable to hold rendering until 2/4 promises have been resolved.

BTW; Your master detail example can be further simplified by simply caching the promise itself rather than the value:

``` javascript

var itemsPromise

function getItems(props) {
  if (!itemsPromise) {
    itemsPromise = new Promise(function(resolve) {
      setTimeout(function() {
        resolve([1, 2, 3, 4, 5])
      })
    }, 700)
  }

  return itemsPromise
}
```
